name: Check domains

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      domain: 
        description: 'name of the domain'
        required: true
        default: 'https://thundra.io'

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Check domain
    strategy:
      matrix:
        domain:
          - ${{github.events.inputs.domain}}

    steps:
      - name: Check domain SSL and registry expire date
        id: check-domain
        uses: codex-team/action-check-domain@v1
        with:
          url: ${{ matrix.domain }}
          
      - run: echo 'SSL cert has ${{ steps.check-domain.outputs.ssl-expire-days-left }} days left'
      - run: echo 'Registry expiration date ${{ steps.check-domain.outputs.paid-till-days-left }} days left'

        
